# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# region_merge.py
# Created on: 2020-10-23 22:41:13.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
BBA_datapoints2_shp = "P:\\Proj6\\USGAP-WVBBA\\Data\\LandCover\\WVworkspace\\ecoclip\\BBA_datapoints2.shp"
wv_eco_shp = "P:\\Proj6\\USGAP-WVBBA\\Data\\LandCover\\WVworkspace\\wv_eco.shp"
point_dataMOD_shp = "P:\\Proj6\\USGAP-WVBBA\\Data\\LandCover\\WVworkspace\\ecoclip\\point_dataMOD.shp"
selcclip = "P:\\Proj6\\USGAP-WVBBA\\Data\\LandCover\\WVworkspace\\selcclip"
serecl = "P:\\Proj6\\USGAP-WVBBA\\Data\\LandCover\\WVworkspace\\ecoclip\\serecl"
sePOLY_shp = "P:\\Proj6\\USGAP-WVBBA\\Data\\LandCover\\WVworkspace\\ecoclip\\sepoly.shp"
point_eco_se_shp = "P:\\Proj6\\USGAP-WVBBA\\Data\\LandCover\\WVworkspace\\ecoclip\\point_eco_se.shp"
point_data_xls = "P:\\Proj6\\USGAP-WVBBA\\Data\\LandCover\\WVworkspace\\ecoclip\\point_data.xls"

# Process: Spatial Join
arcpy.SpatialJoin_analysis(BBA_datapoints2_shp, wv_eco_shp, point_dataMOD_shp, "JOIN_ONE_TO_ONE", "KEEP_ALL", "block_poin \"block_poin\" true true false 254 Text 0 0 ,First,#,P:\\Proj6\\USGAP-WVBBA\\Data\\LandCover\\WVworkspace\\ecoclip\\BBA_datapoints2.shp,block_poin,-1,-1;latitude \"latitude\" true true false 19 Double 0 0 ,First,#,P:\\Proj6\\USGAP-WVBBA\\Data\\LandCover\\WVworkspace\\ecoclip\\BBA_datapoints2.shp,latitude,-1,-1;longitude \"longitude\" true true false 19 Double 0 0 ,First,#,P:\\Proj6\\USGAP-WVBBA\\Data\\LandCover\\WVworkspace\\ecoclip\\BBA_datapoints2.shp,longitude,-1,-1;species \"species\" true true false 254 Text 0 0 ,First,#,P:\\Proj6\\USGAP-WVBBA\\Data\\LandCover\\WVworkspace\\ecoclip\\BBA_datapoints2.shp,species,-1,-1;habitat \"habitat\" true true false 254 Text 0 0 ,First,#,P:\\Proj6\\USGAP-WVBBA\\Data\\LandCover\\WVworkspace\\ecoclip\\BBA_datapoints2.shp,habitat,-1,-1;new_hab \"new_hab\" true true false 254 Text 0 0 ,First,#,P:\\Proj6\\USGAP-WVBBA\\Data\\LandCover\\WVworkspace\\ecoclip\\BBA_datapoints2.shp,new_hab,-1,-1;US_L4CODE \"US_L4CODE\" true true false 10 Text 0 0 ,First,#,P:\\Proj6\\USGAP-WVBBA\\Data\\LandCover\\WVworkspace\\wv_eco.shp,US_L4CODE,-1,-1;US_L4NAME \"US_L4NAME\" true true false 100 Text 0 0 ,First,#,P:\\Proj6\\USGAP-WVBBA\\Data\\LandCover\\WVworkspace\\wv_eco.shp,US_L4NAME,-1,-1;US_L3CODE \"US_L3CODE\" true true false 10 Text 0 0 ,First,#,P:\\Proj6\\USGAP-WVBBA\\Data\\LandCover\\WVworkspace\\wv_eco.shp,US_L3CODE,-1,-1;US_L3NAME \"US_L3NAME\" true true false 100 Text 0 0 ,First,#,P:\\Proj6\\USGAP-WVBBA\\Data\\LandCover\\WVworkspace\\wv_eco.shp,US_L3NAME,-1,-1", "INTERSECT", "", "")

# Process: Reclassify
arcpy.gp.Reclassify_sa(selcclip, "VALUE", "1201 9916 1", serecl, "DATA")

# Process: Raster to Polygon
arcpy.RasterToPolygon_conversion(serecl, sePOLY_shp, "NO_SIMPLIFY", "VALUE")

# Process: Spatial Join (3)
arcpy.SpatialJoin_analysis(point_dataMOD_shp, sePOLY_shp, point_eco_se_shp, "JOIN_ONE_TO_ONE", "KEEP_ALL", "block_poin \"block_poin\" true true false 254 Text 0 0 ,First,#,P:\\Proj6\\USGAP-WVBBA\\Data\\LandCover\\WVworkspace\\ecoclip\\point_dataMOD.shp,block_poin,-1,-1;latitude \"latitude\" true true false 19 Double 0 0 ,First,#,P:\\Proj6\\USGAP-WVBBA\\Data\\LandCover\\WVworkspace\\ecoclip\\point_dataMOD.shp,latitude,-1,-1;longitude \"longitude\" true true false 19 Double 0 0 ,First,#,P:\\Proj6\\USGAP-WVBBA\\Data\\LandCover\\WVworkspace\\ecoclip\\point_dataMOD.shp,longitude,-1,-1;species \"species\" true true false 254 Text 0 0 ,First,#,P:\\Proj6\\USGAP-WVBBA\\Data\\LandCover\\WVworkspace\\ecoclip\\point_dataMOD.shp,species,-1,-1;habitat \"habitat\" true true false 254 Text 0 0 ,First,#,P:\\Proj6\\USGAP-WVBBA\\Data\\LandCover\\WVworkspace\\ecoclip\\point_dataMOD.shp,habitat,-1,-1;new_hab \"new_hab\" true true false 254 Text 0 0 ,First,#,P:\\Proj6\\USGAP-WVBBA\\Data\\LandCover\\WVworkspace\\ecoclip\\point_dataMOD.shp,new_hab,-1,-1;US_L4CODE \"US_L4CODE\" true true false 10 Text 0 0 ,First,#,P:\\Proj6\\USGAP-WVBBA\\Data\\LandCover\\WVworkspace\\ecoclip\\point_dataMOD.shp,US_L4CODE,-1,-1;US_L4NAME \"US_L4NAME\" true true false 100 Text 0 0 ,First,#,P:\\Proj6\\USGAP-WVBBA\\Data\\LandCover\\WVworkspace\\ecoclip\\point_dataMOD.shp,US_L4NAME,-1,-1;US_L3CODE \"US_L3CODE\" true true false 10 Text 0 0 ,First,#,P:\\Proj6\\USGAP-WVBBA\\Data\\LandCover\\WVworkspace\\ecoclip\\point_dataMOD.shp,US_L3CODE,-1,-1;US_L3NAME \"US_L3NAME\" true true false 100 Text 0 0 ,First,#,P:\\Proj6\\USGAP-WVBBA\\Data\\LandCover\\WVworkspace\\ecoclip\\point_dataMOD.shp,US_L3NAME,-1,-1;GRIDCODE \"GRIDCODE\" true true false 0 Long 0 0 ,First,#,P:\\Proj6\\USGAP-WVBBA\\Data\\LandCover\\WVworkspace\\ecoclip\\sePOLY.shp,GRIDCODE,-1,-1", "INTERSECT", "", "")

# Process: Table To Excel
arcpy.TableToExcel_conversion(point_eco_se_shp, point_data_xls, "NAME", "CODE")

